"""Add workspace scoped unique constraints

Revision ID: 52ceb5be9bc4
Revises: 58fc0fe94c1d
Create Date: 2026-07-02 14:56:54.950759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52ceb5be9bc4'
down_revision: Union[str, Sequence[str], None] = '58fc0fe94c1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_access_logs_event_id'), table_name='access_logs')
    op.create_index(op.f('ix_access_logs_event_id'), 'access_logs', ['event_id'], unique=False)
    op.create_unique_constraint('uq_event_workspace', 'access_logs', ['event_id', 'workspace_id'])
    op.drop_index(op.f('ix_machine_identities_arn'), table_name='machine_identities')
    op.create_index(op.f('ix_machine_identities_arn'), 'machine_identities', ['arn'], unique=False)
    op.create_unique_constraint('uq_arn_workspace', 'machine_identities', ['arn', 'workspace_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_arn_workspace', 'machine_identities', type_='unique')
    op.drop_index(op.f('ix_machine_identities_arn'), table_name='machine_identities')
    op.create_index(op.f('ix_machine_identities_arn'), 'machine_identities', ['arn'], unique=True)
    op.drop_constraint('uq_event_workspace', 'access_logs', type_='unique')
    op.drop_index(op.f('ix_access_logs_event_id'), table_name='access_logs')
    op.create_index(op.f('ix_access_logs_event_id'), 'access_logs', ['event_id'], unique=True)
    # ### end Alembic commands ###
